<?php

/**
 * Author:     CriticalGears (http://www.CriticalGears.io)
 * Website:    http://www.CriticalGears.io
 * Support:    http://CriticalGears.io/support-tickets/
 * Version:    2.3.3
 *
 * Copyright:   (c)    CriticalGears.io
 *
 *
 */

define("DEBUG", false);


if (DEBUG) {
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    error_reporting(E_ALL);
} else {
    ini_set('display_errors', 0);
    ini_set('display_startup_errors', 0);
    error_reporting(0);
}

$_BILLING_PERIODS = array(
    "daily" => array("period" => "day", "cycle" => 1),

    "weekly" => array("period" => "week", "cycle" => 1),
    "monthly" => array("period" => "month", "cycle" => 1),
    "bi-monthly" => array("period" => "month", "cycle" => 2),
    "quaterly" => array("period" => "month", "cycle" => 3),
    "semi-annualy" => array("period" => "month", "cycle" => 6),
    "annualy" => array("period" => "year", "cycle" => 1),
);

$PAYPAL_CURRENCIES_LIST = array(
    "AUD" => 'Australian Dollar',
    "BRL" => 'Brazilian Real',
    "CAD" => 'Canadian Dollar',
    "CZK" => 'Czech Koruna',
    "DKK" => 'Danish Krone',
    "EUR" => 'Euro',
    "HKD" => 'Hong Kong Dollar',
    "HUF" => 'Hungarian Forint',
    "ILS" => 'Israeli New Sheqel',
    "JPY" => 'Japanese Yen',
    "MYR" => 'Malaysian Ringgit ',
    "MXN" => 'Mexican Peso',
    "NOK" => 'Norwegian Krone',
    "NZD" => 'New Zealand Dollar',
    "PHP" => 'Philippine Peso',
    "PLN" => 'Polish Zloty',
    "GBP" => 'Pound Sterling',
    "RUB" => 'Russian Ruble',
    "SGD" => 'Singapore Dollar',
    "SEK" => 'Swedish Krona',
    "CHF" => 'Swiss Franc',
    "TWD" => 'Taiwan New Dollar',
    "THB" => 'Thai Baht',
    "TRY" => 'Turkish Lira',
    "USD" => 'U.S. Dollar',
);

$CURRENCY_CODES = array(
    "AED" => "United Arab Emirates Dirham",
    "AFN" => "Afghan Afghani*",
    "ALL" => "Albanian Lek",
    "AMD" => "Armenian Dram",
    "ANG" => "Netherlands Antillean Gulden",
    "AOA" => "Angolan Kwanza*",
    "ARS" => "Argentine Peso*",
    "AUD" => "Australian Dollar",
    "AWG" => "Aruban Florin",
    "AZN" => "Azerbaijani Manat",
    "BAM" => "Bosnia & Herzegovina Convertible Mark",
    "BBD" => "Barbadian Dollar",
    "BDT" => "Bangladeshi Taka",
    "BGN" => "Bulgarian Lev",
    "BHD" => "Bahraini Dinar", // MISSING - ADDED
    "BIF" => "Burundian Franc",
    "BMD" => "Bermudian Dollar",
    "BND" => "Brunei Dollar",
    "BOB" => "Bolivian Boliviano*",
    "BRL" => "Brazilian Real*",
    "BSD" => "Bahamian Dollar",
    "BTN" => "Bhutanese Ngultrum", // MISSING - ADDED
    "BWP" => "Botswana Pula",
    "BYN" => "Belarusian Ruble", // MISSING - ADDED
    "BZD" => "Belize Dollar",
    "CAD" => "Canadian Dollar",
    "CDF" => "Congolese Franc",
    "CHF" => "Swiss Franc",
    "CLP" => "Chilean Peso*",
    "CNY" => "Chinese Renminbi Yuan",
    "COP" => "Colombian Peso*",
    "CRC" => "Costa Rican Colón*",
    "CVE" => "Cape Verdean Escudo*",
    "CZK" => "Czech Koruna*",
    "DJF" => "Djiboutian Franc*",
    "DKK" => "Danish Krone",
    "DOP" => "Dominican Peso",
    "DZD" => "Algerian Dinar",
    "EEK" => "Estonian Kroon*", // MISSING - ADDED
    "EGP" => "Egyptian Pound",
    "ETB" => "Ethiopian Birr",
    "EUR" => "Euro",
    "FJD" => "Fijian Dollar",
    "FKP" => "Falkland Islands Pound*",
    "GBP" => "British Pound",
    "GEL" => "Georgian Lari",
    "GHS" => "Ghanaian Cedi", // MISSING - ADDED
    "GIP" => "Gibraltar Pound",
    "GMD" => "Gambian Dalasi",
    "GNF" => "Guinean Franc*",
    "GTQ" => "Guatemalan Quetzal*",
    "GYD" => "Guyanese Dollar",
    "HKD" => "Hong Kong Dollar",
    "HNL" => "Honduran Lempira*",
    "HRK" => "Croatian Kuna",
    "HTG" => "Haitian Gourde",
    "HUF" => "Hungarian Forint*",
    "IDR" => "Indonesian Rupiah",
    "ILS" => "Israeli New Sheqel",
    "INR" => "Indian Rupee*",
    "ISK" => "Icelandic Króna",
    "JMD" => "Jamaican Dollar",
    "JOD" => "Jordanian Dinar", // MISSING - ADDED
    "JPY" => "Japanese Yen",
    "KES" => "Kenyan Shilling",
    "KGS" => "Kyrgyzstani Som",
    "KHR" => "Cambodian Riel",
    "KMF" => "Comorian Franc",
    "KRW" => "South Korean Won",
    "KWD" => "Kuwaiti Dinar", // MISSING - ADDED
    "KYD" => "Cayman Islands Dollar",
    "KZT" => "Kazakhstani Tenge",
    "LAK" => "Lao Kip*",
    "LBP" => "Lebanese Pound",
    "LKR" => "Sri Lankan Rupee",
    "LRD" => "Liberian Dollar",
    "LSL" => "Lesotho Loti",
    "LTL" => "Lithuanian Litas", // MISSING - ADDED
    "LVL" => "Latvian Lats", // MISSING - ADDED
    "MAD" => "Moroccan Dirham",
    "MDL" => "Moldovan Leu",
    "MGA" => "Malagasy Ariary",
    "MKD" => "Macedonian Denar",
    "MMK" => "Myanmar Kyat", // MISSING - ADDED
    "MNT" => "Mongolian Tögrög",
    "MOP" => "Macanese Pataca",
    "MRO" => "Mauritanian Ouguiya", // MISSING - ADDED
    "MUR" => "Mauritian Rupee*",
    "MVR" => "Maldivian Rufiyaa",
    "MWK" => "Malawian Kwacha",
    "MXN" => "Mexican Peso*",
    "MYR" => "Malaysian Ringgit",
    "MZN" => "Mozambican Metical",
    "NAD" => "Namibian Dollar",
    "NGN" => "Nigerian Naira",
    "NIO" => "Nicaraguan Córdoba*",
    "NOK" => "Norwegian Krone",
    "NPR" => "Nepalese Rupee",
    "NZD" => "New Zealand Dollar",
    "OMR" => "Omani Rial", // MISSING - ADDED
    "PAB" => "Panamanian Balboa*",
    "PEN" => "Peruvian Nuevo Sol*",
    "PGK" => "Papua New Guinean Kina",
    "PHP" => "Philippine Peso",
    "PKR" => "Pakistani Rupee",
    "PLN" => "Polish Złoty",
    "PYG" => "Paraguayan Guaraní*",
    "QAR" => "Qatari Riyal",
    "RON" => "Romanian Leu",
    "RSD" => "Serbian Dinar",
    "RUB" => "Russian Ruble",
    "RWF" => "Rwandan Franc", // MISSING - ADDED
    "SAR" => "Saudi Riyal",
    "SBD" => "Solomon Islands Dollar",
    "SCR" => "Seychellois Rupee",
    "SEK" => "Swedish Krona",
    "SGD" => "Singapore Dollar",
    "SHP" => "Saint Helenian Pound*",
    "SLE" => "Sierra Leonean Leone", // MISSING - ADDED
    "SLL" => "Sierra Leonean Leone", // MISSING - ADDED
    "SOS" => "Somali Shilling",
    "SRD" => "Surinamese Dollar*",
    "STD" => "São Tomé and Príncipe Dobra", // MISSING - ADDED
    "SVC" => "Salvadoran Colón*", // MISSING - ADDED
    "SZL" => "Swazi Lilangeni", // MISSING - ADDED
    "THB" => "Thai Baht",
    "TJS" => "Tajikistani Somoni", // MISSING - ADDED
    "TND" => "Tunisian Dinar", // MISSING - ADDED
    "TOP" => "Tongan Paʻanga", // MISSING - ADDED
    "TRY" => "Turkish Lira",
    "TTD" => "Trinidad and Tobago Dollar",
    "TWD" => "New Taiwan Dollar",
    "TZS" => "Tanzanian Shilling", // MISSING - ADDED
    "UAH" => "Ukrainian Hryvnia",
    "UGX" => "Ugandan Shilling", // MISSING - ADDED
    "USD" => "United States Dollar",
    "USDC" => "USD Coin", // MISSING - ADDED
    "UYU" => "Uruguayan Peso*",
    "UZS" => "Uzbekistani Som",
    "VEF" => "Venezuelan Bolívar", // MISSING - ADDED
    "VND" => "Vietnamese Đồng",
    "VUV" => "Vanuatu Vatu", // MISSING - ADDED
    "WST" => "Samoan Tala", // MISSING - ADDED
    "XAF" => "Central African Cfa Franc",
    "XCD" => "East Caribbean Dollar",
    "XCG" => "Central African Cfa Franc", // MISSING - ADDED (assuming same as XAF)
    "XOF" => "West African Cfa Franc*",
    "XPF" => "Cfp Franc*",
    "YER" => "Yemeni Rial",
    "ZAR" => "South African Rand",
    "ZMW" => "Zambian Kwacha", // MISSING - ADDED
);

$CURRENCY_SYMBOLS = array(
    "AED" => 'د.إ',
    "AFN" => '؋',
    "ALL" => 'Lek',
    "AMD" => '֏',
    "ANG" => 'ƒ',
    "AOA" => 'Kz',
    "ARS" => '$',
    "AUD" => '$',
    "AWG" => 'ƒ',
    "AZN" => '₼',
    "BAM" => 'KM',
    "BBD" => '$',
    "BDT" => '৳',
    "BGN" => 'лв',
    "BHD" => '.د.ب',
    "BIF" => 'FBu',
    "BMD" => '$',
    "BND" => '$',
    "BOB" => '$b',
    "BRL" => 'R$',
    "BSD" => '$',
    "BTN" => 'Nu',
    "BWP" => 'P',
    "BYN" => 'Br',
    "BYR" => 'p.',
    "BZD" => 'BZ$',
    "CAD" => '$',
    "CDF" => 'FC',
    "CHF" => 'CHF',
    "CLP" => '$',
    "CNY" => '¥',
    "COP" => '$',
    "CRC" => '₡',
    "CUP" => '₱',
    "CVE" => 'Esc',
    "CZK" => 'Kč',
    "DJF" => 'Fdj',
    "DKK" => 'kr',
    "DOP" => 'RD$',
    "DZD" => 'د.ج',
    "EEK" => 'kr',
    "EGP" => '£',
    "ETB" => 'Br',
    "EUR" => '€',
    "FJD" => '$',
    "FKP" => '£',
    "GBP" => '£',
    "GEL" => '₾',
    "GHC" => '¢',
    "GHS" => 'GH₵',
    "GIP" => '£',
    "GMD" => 'D',
    "GNF" => 'FG',
    "GTQ" => 'Q',
    "GYD" => '$',
    "HKD" => '$',
    "HNL" => 'L',
    "HRK" => 'kn',
    "HTG" => 'G',
    "HUF" => 'Ft',
    "IDR" => 'Rp',
    "ILS" => '₪',
    "IMP" => '£',
    "INR" => '₹',
    "IRR" => '﷼',
    "ISK" => 'kr',
    "JEP" => '£',
    "JMD" => 'J$',
    "JOD" => 'JD',
    "JPY" => '¥',
    "KES" => 'KSh',
    "KGS" => 'лв',
    "KHR" => '៛',
    "KMF" => 'CF',
    "KPW" => '₩',
    "KRW" => '₩',
    "KWD" => 'د.ك',
    "KYD" => '$',
    "KZT" => 'лв',
    "LAK" => '₭',
    "LBP" => '£',
    "LKR" => '₨',
    "LRD" => '$',
    "LSL" => 'L',
    "LTL" => 'Lt',
    "LVL" => 'Ls',
    "LYD" => 'ل.د',
    "MAD" => 'د.م.',
    "MDL" => 'L',
    "MGA" => 'Ar',
    "MKD" => 'ден',
    "MMK" => 'K',
    "MNT" => '₮',
    "MOP" => 'MOP$',
    "MRU" => 'UM',
    "MUR" => '₨',
    "MVR" => 'Rf',
    "MWK" => 'MK',
    "MXN" => '$',
    "MYR" => 'RM',
    "MZN" => 'MT',
    "NAD" => '$',
    "NGN" => '₦',
    "NIO" => 'C$',
    "NOK" => 'kr',
    "NPR" => '₨',
    "NZD" => '$',
    "OMR" => '﷼',
    "PAB" => 'B/.',
    "PEN" => 'S/.',
    "PGK" => 'K',
    "PHP" => '₱',
    "PKR" => '₨',
    "PLN" => 'zł',
    "PYG" => 'Gs',
    "QAR" => '﷼',
    "RON" => 'lei',
    "RSD" => 'Дин.',
    "RUB" => 'руб',
    "RWF" => 'RFr',
    "SAR" => '﷼',
    "SBD" => '$',
    "SCR" => '₨',
    "SDG" => 'ج.س.',
    "SEK" => 'kr',
    "SGD" => '$',
    "SHP" => '£',
    "SLE" => 'Le',
    "SLL" => 'Le',
    "SOS" => 'S',
    "SRD" => '$',
    "STN" => 'Db',
    "SVC" => '$',
    "SYP" => '£',
    "SZL" => 'E',
    "THB" => '฿',
    "TJS" => 'ЅМ',
    "TMT" => 'T',
    "TND" => 'د.ت',
    "TOP" => 'T$',
    "TRY" => '₺',
    "TTD" => 'TT$',
    "TVD" => '$',
    "TWD" => 'NT$',
    "TZS" => 'TSh',
    "UAH" => '₴',
    "UGX" => 'USh',
    "USD" => '$',
    "USDC" => '$',
    "UYU" => '$U',
    "UZS" => 'лв',
    "VEF" => 'Bs',
    "VES" => 'Bs.S',
    "VND" => '₫',
    "VUV" => 'VT',
    "WST" => 'WS$',
    "XAF" => 'FCFA',
    "XCD" => '$',
    "XOF" => 'CFA',
    "XPF" => '₣',
    "YER" => '﷼',
    "ZAR" => 'S',
    "ZMW" => 'K',
    "ZWD" => 'Z$'
);


$CURRENCY_UNHEX_CODES = array(
    "ALL" => '4C656B', // Lek
    "AFN" => 'D88B', // ؋
    "ARS" => '24', // $
    "AWG" => 'C692', // ƒ
    "AUD" => '24', // $
    "BSD" => '24', // $
    "BBD" => '24', // $
    "BZD" => '425A24', // BZ$
    "BMD" => '24', // $
    "BOB" => '2462', // $b
    "BAM" => '4B4D', // KM
    "BWP" => '50', // P
    "BGN" => 'D0BBD0B2', // лв
    "BRL" => '5224', // R$
    "BND" => '24', // $
    "KHR" => 'E17E9B', // ៛
    "CAD" => '24', // $
    "KYD" => '24', // $
    "CLP" => '24', // $
    "CNY" => 'C2A5', // ¥
    "COP" => '24', // $
    "CRC" => 'E282A1', // ₡
    "HRK" => '6B6E', // kn
    "CZK" => '4BC48D', // Kč
    "DKK" => '6B72', // kr
    "DOP" => '524424', // RD$
    "XCD" => '24', // $
    "EGP" => 'C2A3', // £
    "EUR" => 'E282AC', // €
    "FKP" => 'C2A3', // £
    "FJD" => '24', // $
    "GIP" => 'C2A3', // £
    "GTQ" => '51', // Q
    "GYD" => '24', // $
    "HNL" => '4C', // L
    "HKD" => '24', // $
    "HUF" => '4674', // Ft
    "ISK" => '6B72', // kr
    "INR" => 'E282B9', // ₹
    "IDR" => '5270', // Rp
    "ILS" => 'E282AA', // ₪
    "JMD" => '4A24', // J$
    "JPY" => 'C2A5', // ¥
    "KZT" => 'D0BBD0B2', // лв
    "KRW" => 'E282A9', // ₩
    "KGS" => 'D0BBD0B2', // лв
    "LAK" => 'E282AD', // ₭
    "LBP" => 'C2A3', // £
    "LRD" => '24', // $
    "MKD" => 'D0B4D0B5D0BD', // ден
    "MYR" => '524D', // RM
    "MUR" => 'E282A8', // ₨
    "MXN" => '24', // $
    "MNT" => 'E282AE', // ₮
    "MZN" => '4D54', // MT
    "NAD" => '24', // $
    "NPR" => 'E282A8', // ₨
    "ANG" => 'C692', // ƒ
    "NZD" => '24', // $
    "NIO" => '4324', // C$
    "NGN" => 'E282A6', // ₦
    "NOK" => '6B72', // kr
    "PKR" => 'E282A8', // ₨
    "PAB" => '422F2E', // B/.
    "PYG" => '4773', // Gs
    "PEN" => '532F2E', // S/.
    "PHP" => 'E282B1', // ₱
    "PLN" => '7AC582', // zł
    "QAR" => 'EFB9B4', // ﷼
    "RON" => '6C6569', // lei
    "RUB" => 'D180D183D0B1', // руб
    "SHP" => 'C2A3', // £
    "SAR" => 'EFB9B4', // ﷼
    "RSD" => 'D094D0B8D0BD2E', // Дин.
    "SCR" => 'E282A8', // ₨
    "SGD" => '24', // $
    "SBD" => '24', // $
    "SOS" => '53', // S
    "ZAR" => '52', // R
    "LKR" => 'E282A8', // ₨
    "SEK" => '6B72', // kr
    "CHF" => '434846', // CHF
    "SRD" => '24', // $
    "TWD" => '4E5424', // NT$
    "THB" => 'E0B8BF', // ฿
    "TTD" => '545424', // TT$
    "UAH" => 'E282B4', // ₴
    "GBP" => 'C2A3', // £
    "USD" => '24', // $
    "UYU" => '2455', // $U
    "UZS" => 'D0BBD0B2', // лв
    "VND" => 'E282AB', // ₫
    "YER" => 'EFB9B4', // ﷼
);
